runtime: python27
api_version: 1
threadsafe: true
runtime: nodejs

handlers:
- url: /
  static_files: build-2/build/index.html
  upload: build-2/build/index.html

- url: /
  static_dir: build-2/build
